hpc <- read.table("household_power_consumption.txt", sep = ";", header = TRUE, na.strings=c("NA", "-", "?"))
hpc2 = hpc[hpc$Date == "1/2/2007" | hpc$Date == "2/2/2007",]
hpc2$DateTime <- paste(hpc2$Date, hpc2$Time)
hpc2$DateTime <- strptime(hpc2$DateTime, "%d/%m/%Y %H:%M:%S")
Sys.setlocale("LC_TIME", "English")
png("plot4.png")
par(mfrow=c(2,2))
plot(hpc2$DateTime, hpc2$Global_active_power, type = "l", ylab = "Global Active Power", xlab = "")
plot(hpc2$DateTime, hpc2$Voltage, type = "l", ylab = "Voltage", xlab = "datetime")
plot(hpc2$DateTime, hpc2$Sub_metering_1, type = "l", ylab = "Energy sub metering", xlab = "")
lines(hpc2$DateTime, hpc2$Sub_metering_2, col = "red")
lines(hpc2$DateTime, hpc2$Sub_metering_3, col = "blue")
plot(hpc2$DateTime, hpc2$Global_reactive_power, type = "l", ylab = "Global_reactive_power", xlab = "datetime")
dev.off()